### ISSUE TITLE
Dying light 2

### ISSUE THREAD

**Issue by RucoR32** [Nukem9/dlssg-to-fsr3#268]
Any advance with dying light 2 mod nukem FG??

**Comment by ImASadBoy** [comment]
I can't get it to work, I'm trying many different things

**Comment by ImASadBoy** [comment]
I got Dying Light 2 to work! I'm updating the wiki right now to explain the process

**Comment by fatezerotwoxyz** [comment]
> I got Dying Light 2 to work! I'm updating the wiki right now to explain the process

How to make it work?

**Comment by ImASadBoy** [comment]
> > I got Dying Light 2 to work! I'm updating the wiki right now to explain the process
> 
> How to make it work?

updated the wiki with instructions 
https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2

**Comment by RucoR32** [comment]
I just tried to do it but I do something wrong because even though the FG option appears it is like it is not implemented because the fps does not increase... maybe you could send me a video to see how to do it please :(

**Comment by RucoR32** [comment]
> > > ¡Conseguí que Dying Light 2 funcionara! Estoy actualizando la wiki ahora mismo para explicar el proceso
> > 
> > 
> > ¿Cómo hacer que funcione?
> 
> Se actualizó la wiki con instrucciones https://github.com/Nukem9/dlssg-to-fsr3/wiki/Dying-Light-2
I just tried to do it but I do something wrong because even though the FG option appears it is like it is not implemented because the fps does not increase... maybe you could send me a video to see how to do it please :(

**Comment by ImASadBoy** [comment]
> I just tried to do it but I do something wrong because even though the FG option appears it is like it is not implemented because the fps does not increase... maybe you could send me a video to see how to do it please :(

Here is a video tutorial exposing my messy desktop https://streamable.com/btg0lg

**Comment by RucoR32** [comment]
> > Solo intenté hacerlo pero hago algo mal porque aunque aparece la opción FG es como si no estuviera implementada porque los fps no aumentan... tal vez podrían enviarme un video para ver cómo hacerlo por favor :(
> 
> Aquí hay un video tutorial que expone mi escritorio desordenado https://streamable.com/
Thanx my Bro... You are god

**Comment by alex-enginity** [comment]
For me it shows the option but it crashes if I enable it and then it will crash every time the game is about to resume.

**Comment by juhannnnnn** [comment]
> > I just tried to do it but I do something wrong because even though the FG option appears it is like it is not implemented because the fps does not increase... maybe you could send me a video to see how to do it please :(
> 
> Here is a video tutorial exposing my messy desktop https://streamable.com/btg0lg

i have followed ur steps and managed to unlock frame generation. but the thing is the generated frames dont feel that much smooth at all despite the nvidia overlay showing that fps has doubled.

**Comment by nekusu** [comment]
Same here. Unfortunately, I don't think it's actually working. The FPS double but it is not smoother, it may just be duplicating frames. With the LukeFZ mod there is a noticeable additional smoothness, but it would be great to play with DLSS for the upscaling instead of FSR.

**Comment by ImASadBoy** [comment]
> Tried it, unfortunately it didn't improve the smoothness but reduced it even though the fps was much higher with FG turned on, it seems like something is still not implemented correctly.

Looks like the game sometimes doesn't listen to the path override and uses default nvidia fg, but since old RTX cards don't have the new OFWA, it falls back on duplicating frames instead of generating new games. I haven't found a solution to this yet, I think the problem is with either dlsstweaks or this mod.

**Comment by Knell2231** [comment]
> Looks like the game sometimes doesn't listen to the path override and uses default nvidia fg, but since old RTX cards don't have the new OFWA, it falls back on duplicating frames instead of generating new games. I haven't found a solution to this yet, I think the problem is with either dlsstweaks or this mod.

What is OFWA?, am using a 2060, and the mod even after following your instructions still seems to crash just like what is happening to [alex-enginity](https://github.com/alex-enginity),

> For me it shows the option but it crashes if I enable it and then it will crash every time the game is about to resume.

 i thought it would only crash the first time but it seems that was not the case, maybe because im using a cracked version? even though the cracked version is updated to the latest version.

**Comment by ImASadBoy** [comment]
> > Looks like the game sometimes doesn't listen to the path override and uses default nvidia fg, but since old RTX cards don't have the new OFWA, it falls back on duplicating frames instead of generating new games. I haven't found a solution to this yet, I think the problem is with either dlsstweaks or this mod.
> 
> What is OFWA?, am using a 2060, and the mod even after following your instructions still seems to crash just like what is happening to [alex-enginity](https://github.com/alex-enginity),
> 
> > For me it shows the option but it crashes if I enable it and then it will crash every time the game is about to resume.
> 
> i thought it would only crash the first time but it seems that was not the case, maybe because im using a cracked version? even though the cracked version is updated to the latest version.
> 
> EDIT : Might also be helpful if there are graphical settings ingame that needs to be changed to prevent crashes upon load, also in the dlssg_to_fsr3.log this line appears as the game crashes : Evaluation call failed with status -7FFFFFF3.

Optical Flow Accellerator, the rtx4070 have an improved version of it.

Sadly the mod doesn't work super good with dl2 right now

**Comment by Knell2231** [comment]
> Optical Flow Accellerator, the rtx4070 have an improved version of it.
> 
> Sadly the mod doesn't work super good with dl2 right now

Got it to work, somehow, started a new game, skipped the tutorial. Problem is it only works when i view the game while holding alt-tab, the moment i choose the game as my main window it crashes instantly, so yeah its still quite unstable.

When viewing the game while holding alt tab its super smooth, no problems at all. Maybe the main problem lies somewhere in there?

Another option is to use LukeFZ's FG, but from the videos ive seen using it with DL2, is that the ui gets messed up real bad.

**Comment by ImASadBoy** [comment]
> > Optical Flow Accellerator, the rtx4070 have an improved version of it.
> > Sadly the mod doesn't work super good with dl2 right now
> 
> Got it to work, somehow, started a new game, skipped the tutorial. Problem is it only works when i view the game while holding alt-tab, the moment i choose the game as my main window it crashes instantly, so yeah its still quite unstable.
> 
> When viewing the game while holding alt tab its super smooth, no problems at all. Maybe the main problem lies somewhere in there?
> 
> Another option is to use LukeFZ's FG, but from the videos ive seen using it with DL2, is that the ui gets messed up real bad.

Can you send a pastebin of your dllstweaks.ini? Check othe people that had the same issues uphere, we already managed to help them

**Comment by Knell2231** [comment]
> Can you send a pastebin of your dllstweaks.ini? Check othe people that had the same issues uphere, we already managed to help them

https://pastebin.com/UrGqZHjG - dlsstweaks.ini
This might also help : https://pastebin.com/u78kRgAW - dlsstweaks.log

**Comment by ImASadBoy** [comment]
> > Can you send a pastebin of your dllstweaks.ini? Check othe people that had the same issues uphere, we already managed to help them
> 
> https://pastebin.com/UrGqZHjG - dlsstweaks.ini This might also help : https://pastebin.com/u78kRgAW - dlsstweaks.log

What game version is it?

**Comment by Knell2231** [comment]
1.14

**Comment by ImASadBoy** [comment]
> 1.14

I don't know how to help then :/ your dlsstweaks.ini looks fine and if you followed every step it should be working fine

**Comment by Knell2231** [comment]
> I don't know how to help then :/ your dlsstweaks.ini looks fine and if you followed every step it should be working fine
> 
> Try deleting all the files in the folder, verify the game through steam or epic games in order to get all the clean files and then do that again

Im actually playing on a cracked version so the best i can do is delete then reinstall which i already did, and i actually tried installing the non dlss tweaks version of the mod, but same thing still happened, guess i would just have to wait to get it fixed.

Anyway, thanks for taking the time to assist me in my concerns.

**Comment by deveers** [comment]
This mod doesn't work right on dying light 2. like steam overlay says my fps increased by 50% but it looks like it's the same or even lower fps

I tried out lukefz's fsr 3 mod and that actually looks like it's running at 144fps

**Comment by Capoos** [comment]
> > 1.14
> 
> 我不知道该怎么帮忙：/您的 DLSSTWEAKS.ini 看起来不错，如果您遵循每个步骤，它应该可以正常工作
> 
> 尝试删除文件夹中的所有文件，通过Steam或史诗游戏验证游戏，以获取所有干净的文件，然后再次执行此操作

I'm using 2060laptop,The latest driver,Dying light 2 is steam genuine,All the situation is the same as him,As long as you open FG and continue the game, it will definitely crash,win+tab observation will not crash,The game will crash immediately if you treat the game as the main window,Check the log and find that the end is:[error] Evaluation call failed with status -7FFFFFF3.What is the cause of this?

**Comment by deveers** [comment]
> > > 1.14
> > 
> > 
> > 我不知道该怎么帮忙：/您的 DLSSTWEAKS.ini 看起来不错，如果您遵循每个步骤，它应该可以正常工作
> > 尝试删除文件夹中的所有文件，通过Steam或史诗游戏验证游戏，以获取所有干净的文件，然后再次执行此操作
> 
> I'm using 2060laptop,The latest driver,Dying light 2 is steam genuine,All the situation is the same as him,As long as you open FG and continue the game, it will definitely crash,win+tab observation will not crash,The game will crash immediately if you treat the game as the main window,Check the log and find that the end is:[error] Evaluation call failed with status -7FFFFFF3.What is the cause of this?

It happened to me too, I had other dlls and mods in my game, I uninstalled from steam, deleted the dying light 2 folder, reinstalled and then installed the mod and it worked

**Comment by ginpigin** [comment]
Evaluation call failed with status -7FFFFFF3

**Comment by multres** [comment]
Same error as the guys above ; - Evaluation call failed with status -7FFFFFF3.

**Comment by ginpigin** [comment]
version 0.81 Evaluation call failed with status 8000000D
